<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Login_DataDriven</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c0fde6ed-dcd8-4809-8614-7e06dc36d11f</testSuiteGuid>
   <testCaseLink>
      <guid>f541da14-846a-4ff4-93e3-3255a28aec7e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenarios/Login/Login_Valid</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4fa9bfe4-0653-45f9-b37b-2370307aa6f3</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>3</value>
         </iterationEntity>
         <testDataId>Data Files/TestData/loginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4fa9bfe4-0653-45f9-b37b-2370307aa6f3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>7f2d1d99-81a0-4437-83bc-a03199cb5807</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4fa9bfe4-0653-45f9-b37b-2370307aa6f3</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>a81222af-952b-40ed-ba82-64a59ef0c9ab</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>96ae0b40-e041-49e7-b658-719402b0bc86</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenarios/Login/Login_InvalidPassword</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a4cf2df0-3ba8-4f1d-9586-04885296af90</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/TestData/loginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c886f48-6e68-4e47-aef8-c122ef2d073c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a4cf2df0-3ba8-4f1d-9586-04885296af90</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>babf6d95-f4c7-4217-b18b-0ffd60f63435</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a4cf2df0-3ba8-4f1d-9586-04885296af90</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>31c09ca1-77b3-4302-a9e7-208e404a025e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4854c5d5-43d6-4b7a-b9ed-d5f8779a64c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Scenarios/Login/Login_Invalid_Username_and_Password</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>65d0a702-ae72-43a1-9fb6-a6029cc28933</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2</value>
         </iterationEntity>
         <testDataId>Data Files/TestData/loginData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63c96309-8d26-4672-82a2-2d1f7e8f4242</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>65d0a702-ae72-43a1-9fb6-a6029cc28933</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>fef23a94-bbbb-4481-b818-4c54832bd4d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>65d0a702-ae72-43a1-9fb6-a6029cc28933</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>e031df3e-8eba-4e8c-acf1-e4736cdf08cd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
