<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>grandTotal</name>
   <tag></tag>
   <elementGuidId>d435c842-a0de-42f4-8cf2-92995408937b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tfoot/tr/th[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tfoot.table > tr > th:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>072cbcf1-c88b-44d1-a1f4-64fee08cc94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>₹1,706.00</value>
      <webElementGuid>797869e3-56a5-4e85-8d5b-b954c6ae8f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/div[@class=&quot;container&quot;]/app-checkout[@class=&quot;ng-star-inserted&quot;]/mat-card[@class=&quot;mat-mdc-card mdc-card my-4 ng-star-inserted&quot;]/mat-card-content[@class=&quot;mat-mdc-card-content p-2&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/table[@class=&quot;table ng-star-inserted&quot;]/tfoot[@class=&quot;table&quot;]/tr[1]/th[2]</value>
      <webElementGuid>921f1355-aaf4-441f-bfd3-7a1641fd26e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grand Total'])[1]/following::th[1]</value>
      <webElementGuid>a00251d4-42e8-4494-9e92-f93439c2f08c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹1,234.00'])[2]/following::th[2]</value>
      <webElementGuid>6d75eaf8-4fdc-44ec-a1ad-960f92f7f925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API details'])[1]/preceding::th[1]</value>
      <webElementGuid>b7d6a8dc-eafc-49ef-bcbe-d2ca3b742aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GitHub'])[2]/preceding::th[1]</value>
      <webElementGuid>1f8d8a20-4177-4aa2-8ab1-5a3f97f32c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='₹1,706.00']/parent::*</value>
      <webElementGuid>915450a5-1d84-4ae6-a921-92aaf74b7732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tfoot/tr/th[2]</value>
      <webElementGuid>bc606c9e-6c1d-4a32-b732-d10921f73912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = '₹1,706.00' or . = '₹1,706.00')]</value>
      <webElementGuid>1d1b0340-6e44-4361-b818-01110146e964</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
