<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errorMessageLastNameisrequired</name>
   <tag></tag>
   <elementGuidId>bc198d5e-4918-4803-bcd7-236528aa65de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-mdc-error-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-error[@id='mat-mdc-error-8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-error</value>
      <webElementGuid>9dee608f-26ce-4936-b3e2-b2e8d7916656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>af8f53ac-b680-4ed9-96da-62b53f4733f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-form-field-error mat-mdc-form-field-bottom-align ng-tns-c508571215-15 ng-star-inserted</value>
      <webElementGuid>5cda8bd5-3d9d-4282-befa-d4d6cfa1141b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>c66c10e1-9142-4c3c-b39e-7b3b304a31d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-mdc-error-8</value>
      <webElementGuid>724e8c2f-112c-498b-94b6-3f51448cbe20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last Name is required</value>
      <webElementGuid>a25255c5-eef9-48a2-b772-c3edc143730d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-mdc-error-8&quot;)</value>
      <webElementGuid>bb355ec3-3822-4548-8df9-56a62832e9d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//mat-error[@id='mat-mdc-error-8']</value>
      <webElementGuid>9643258a-54c8-4b26-a8ec-2e46b8673e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last name'])[1]/following::mat-error[1]</value>
      <webElementGuid>065df387-78d0-4e9a-977e-11afad944cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name is required'])[1]/following::mat-error[1]</value>
      <webElementGuid>791d6f1b-3b64-4a58-af26-d671eea395aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User name'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>cd29c04a-b1f3-453e-94a3-648aa3100f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Name is required'])[1]/preceding::mat-error[1]</value>
      <webElementGuid>05db7652-c1c3-4c1b-ab1c-79fe2bde79e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Last Name is required']/parent::*</value>
      <webElementGuid>a99e939a-19d4-4424-878f-e59776f40ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-form-field[2]/div[2]/div/mat-error</value>
      <webElementGuid>8527d723-bd41-43fb-ae55-cd2329f64c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//mat-error[@id = 'mat-mdc-error-8' and (text() = 'Last Name is required' or . = 'Last Name is required')]</value>
      <webElementGuid>fc9d93c7-324e-47fd-85b8-d384e8ef87ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
