<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>labelItemsperpage</name>
   <tag></tag>
   <elementGuidId>3ac3f232-60a6-418f-881b-67de9a595957</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-paginator-page-size-label-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-paginator-page-size-label-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98dcc91a-d5c0-411f-b68d-fc0f930d321b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-mdc-paginator-page-size-label</value>
      <webElementGuid>5af68e41-d378-4f24-b889-f007e09e419d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-paginator-page-size-label-0</value>
      <webElementGuid>fcd0d906-50a2-4894-81db-1356eb2b2198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Items per page: </value>
      <webElementGuid>6ed7d31d-e3d0-4d7e-b2f4-0935342b6cd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-paginator-page-size-label-0&quot;)</value>
      <webElementGuid>f69667b0-eaa5-4bdb-939a-8dc6f05bbdf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mat-paginator-page-size-label-0']</value>
      <webElementGuid>c0615710-e451-4019-b0c4-d842cb5856f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='₹2,232.00'])[1]/following::div[4]</value>
      <webElementGuid>c61d4122-614e-486e-b69a-cc8fb3490ab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This Storm'])[1]/following::div[4]</value>
      <webElementGuid>c8771de6-7467-4e72-a549-ab7a0b28220a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API details'])[1]/preceding::div[19]</value>
      <webElementGuid>6d5c86ca-20d7-4b6f-b297-b337ad8a699e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GitHub'])[2]/preceding::div[20]</value>
      <webElementGuid>64d697b9-1507-40d0-8313-511dee2185c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Items per page:']/parent::*</value>
      <webElementGuid>42045ccc-d798-4bb0-a704-7ca9a6657dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-paginator/div/div/div/div</value>
      <webElementGuid>8e6beacb-943c-4560-bcfb-10a7bda64a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mat-paginator-page-size-label-0' and (text() = ' Items per page: ' or . = ' Items per page: ')]</value>
      <webElementGuid>b8c7e139-b5e1-4d87-9343-04aaa579f088</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
